title: Angeline Words
email: seokbong60@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the Angeline Words
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

nickname: recoma
email: seokbong60@gmail.com
user_description: 아 인생 날로 먹고 싶다 ㅠㅠ
profile_image: /assets/img/profile.jpg

social:
  github: https://github.com/recoma96
  email: seokbong60@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# blog system configs
paginate: 10
paginate_path: "/posts/:num/"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
